[package]
name = "mos6502_atari_7800_example"
version = "0.1.0"
edition = "1"

[[rom]]
name = "example"
path = "src/cart.op"
target = "mos6502-atari-7800"
format = "a78"

[dependencies]
std = { version = "0.5.0", git = "https://github.com/op-language/std" }

[target]
default = "mos6502-atari-7800"
