[package]
name = "wdc65c816_nintendo_snes_example"
version = "0.1.0"
edition = "1"

[[rom]]
name = "example"
path = "src/cart.op"
target = "wdc65c816-nintendo-snes"
format = "snes"

[dependencies]
std = { version = "0.5.0", git = "https://github.com/op-language/std" }

[target]
default = "wdc65c816-nintendo-snes"
