[package]
name = "z80_sega_sg1000_example"
version = "0.1.0"
edition = "1"

[[rom]]
name = "example"
path = "src/cart.op"
target = "z80-sega-sg1000"
format = "sms"

[dependencies]
std = { version = "0.5.0", git = "https://github.com/op-language/std" }

[target]
default = "z80-sega-sg1000"
