[workspace]
members = [
    "crates/op-common",
    "crates/op-target",
    "crates/op-ir",
    "crates/op-diagnostics",
    "crates/opc",
]
resolver = "2"

[workspace.package]
version = "0.4.0"
edition = "2021"
authors = ["Dave Grantham <dwg@linuxprogrammer.org>"]
license = "Apache 2.0"
repository = "https://github.com/op-language/op"
homepage = "https://github.com/op-language/op"

[workspace.dependencies]
op-common = { path = "crates/op-common" }
op-target = { path = "crates/op-target" }
op-ir = { path = "crates/op-ir" }
op-diagnostics = { path = "crates/op-diagnostics" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
thiserror = "2"
logos = "0.16"
lalrpop = "0.23"
lalrpop-util = "0.23"
clap = { version = "4", features = ["derive"] }
toml = "1.1"

[profile.release]
opt-level = 1
