[package]
name = "opc"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "The Op compiler"

[[bin]]
name = "opc"
path = "src/main.rs"

[lib]
name = "opc"
path = "src/lib.rs"

[dependencies]
op-common.workspace = true
op-target.workspace = true
op-ir.workspace = true
op-diagnostics.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
logos.workspace = true
lalrpop-util.workspace = true
clap.workspace = true

[build-dependencies]
lalrpop.workspace = true

[dev-dependencies]
serde_json.workspace = true