[package]
name = "vl65nc02_atari_lynx_example"
version = "0.1.0"
edition = "1"

[[rom]]
name = "example"
path = "src/cart.op"
target = "vl65nc02-atari-lynx"
format = "lnx"

[dependencies]
std = { version = "0.5.0", git = "https://github.com/op-language/std" }

[target]
default = "vl65nc02-atari-lynx"
